export const MYDATA = [
  {
    row_id: 5,
    'Sygnatura czasowa': '27.05.2021, 19:29:05',
    'Adres e-mail': 'adam@walukiewicz.eu',
    Lekarz: 'Adam Walukiewicz',
    '1. Inicjały pacjenta:': 'ts',
    '2. Wiek pacjenta:': '23',
    '3. Jak długo pacjent stara się o potomstwo?': '2',
    '4. Ile razy pacjent wykonał badania nasienia w czasie starań o ciążę?':
      '2',
    '4.1 Jeżli wykonywał, to jakie badania?': 'Normospermia,OAT I',
    '5. Choroby towarzyszące:': 'Urologiczne',
    '6. Ocena ginekologiczna czynnika żeńskiego:': 'Płodna',
    '7. Czy pacjent chorował w ostatnim czasie na COVID?': 'Nie',
    '8. Czy jest zaszczepiony przeciw SARS-COV-2?': 'Nie',
    '8.1 Jeżeli tak, to ile dawek?': '-',
    '8.2 Czy wystąpiły odczyny poszczepienne ?': '-',
    '9. Czy wykonywał badania nasienia w okresie około-COVID?': 'Nie',
    '9.1 Jeśli tak, to czy nastąpiło:': '-',
    '10. Czy była stosowana / stosuje terapia poprawiającą płodność?': 'Nie',
    '10.1 Jeśli tak to jaka?': '-',
    '11. Czy stosował / stosuje terapie stresu oksydacyjnego (suplementy)?':
      'Nie',
    '11.1 Jeśli tak, to jaki preparat i jak długo?': '-',
    '12. Dodatkowy komentarz:': '-',
  },
  {
    row_id: 6,
    'Sygnatura czasowa': '27.05.2021, 19:30:39',
    'Adres e-mail': 'adam@walukiewicz.eu',
    Lekarz: 'Adam Walukiewicz',
    '1. Inicjały pacjenta:': 'ts2',
    '2. Wiek pacjenta:': '32',
    '3. Jak długo pacjent stara się o potomstwo?': '32',
    '4. Ile razy pacjent wykonał badania nasienia w czasie starań o ciążę?':
      '32',
    '4.1 Jeżli wykonywał, to jakie badania?': 'Normospermia,OAT I',
    '5. Choroby towarzyszące:': 'Urologiczne',
    '6. Ocena ginekologiczna czynnika żeńskiego:': 'Płodna',
    '7. Czy pacjent chorował w ostatnim czasie na COVID?': 'Nie',
    '8. Czy jest zaszczepiony przeciw SARS-COV-2?': 'Nie',
    '8.1 Jeżeli tak, to ile dawek?': '-',
    '8.2 Czy wystąpiły odczyny poszczepienne ?': '-',
    '9. Czy wykonywał badania nasienia w okresie około-COVID?': 'Nie',
    '9.1 Jeśli tak, to czy nastąpiło:': '-',
    '10. Czy była stosowana / stosuje terapia poprawiającą płodność?': 'Nie',
    '10.1 Jeśli tak to jaka?': '-',
    '11. Czy stosował / stosuje terapie stresu oksydacyjnego (suplementy)?':
      'Nie',
    '11.1 Jeśli tak, to jaki preparat i jak długo?': '-',
    '12. Dodatkowy komentarz:': '-',
  },
  {
    row_id: 7,
    'Sygnatura czasowa': '27.05.2021, 19:31:48',
    'Adres e-mail': 'adam@walukiewicz.eu',
    Lekarz: 'Adam Walukiewicz',
    '1. Inicjały pacjenta:': 'ts3',
    '2. Wiek pacjenta:': '32',
    '3. Jak długo pacjent stara się o potomstwo?': '4',
    '4. Ile razy pacjent wykonał badania nasienia w czasie starań o ciążę?':
      '2',
    '4.1 Jeżli wykonywał, to jakie badania?': '-',
    '5. Choroby towarzyszące:': '-',
    '6. Ocena ginekologiczna czynnika żeńskiego:': 'Płodna',
    '7. Czy pacjent chorował w ostatnim czasie na COVID?': 'Nie',
    '8. Czy jest zaszczepiony przeciw SARS-COV-2?': 'Nie',
    '8.1 Jeżeli tak, to ile dawek?': '-',
    '8.2 Czy wystąpiły odczyny poszczepienne ?': '-',
    '9. Czy wykonywał badania nasienia w okresie około-COVID?': 'Nie',
    '9.1 Jeśli tak, to czy nastąpiło:': '-',
    '10. Czy była stosowana / stosuje terapia poprawiającą płodność?': 'Nie',
    '10.1 Jeśli tak to jaka?': '-',
    '11. Czy stosował / stosuje terapie stresu oksydacyjnego (suplementy)?':
      'Nie',
    '11.1 Jeśli tak, to jaki preparat i jak długo?': '-',
    '12. Dodatkowy komentarz:': '-',
  },
];